# this is a tutorial from:
	# https://www.analyticsvidhya.com/blog/2017/03/beginners-guide-on-web-scraping-in-r-using-rvest-with-hands-on-knowledge/

# libraries
library("rvest")
library("tidyverse")


# Introduction

# there are 4 basic ways to get data from the web
	# (1) Human Copy-Paste
		# inefficient
	# (2) Text Pattern Matching
		# using regular expression matching facilities in programming languages
	# (3) API Interface
		# many websites like Facbook or Twitter have public and private APIs
		# these can be used to retrieve data in a perscribed format
	# (4) DOM Parsing
		# programs utilize web browsers to retrieve dynamic content generated by client-side scripts
		# also possible to parse web pages into a DOM tree, based on which programs can retrieve parts of these pages

# this tutorial will focus on the DOM parsing approach
	# and rely on CSS selectors of a webpage 




# Getting Started

# Specifying the url for desired website to be scrapped
url <- 'http://www.imdb.com/search/title?count=100&release_date=2016,2016&title_type=feature'

# Reading the HTML code from the website
webpage <- read_html(url)

# we'll want the following data from the website
	# Rank - from 1 to 100 in the 100 most popular films of 2016
	# Title 
	# Description 
	# Runtime 
	# Genre
	# Rating
	# Metascore - IMDB score
	# Votes = votes cast in favor of the feature films
	# Gross Earnings
	# Director
	# Main Actor/Actress - in cases of multiple actors or actresses we'll only take the first

# first we'll get the rankings
	# open the imdb page
	# select the ranking with selector gadget to get the path
	# then run the following code
		# the second argument of html_nodes() is the path specified by selector gadget

# use CSS selectors to scrap the rankings section
rank_data_html <- html_nodes(webpage, '.text-primary')

# convert the ranking data to text
rank_data <- html_text(rank_data_html)

# convert from character to numeric vector
rank_data <- as.numeric(rank_data) 

# do the same to get the titles
	# if selecting an element you can double click a false positive selection

title_data_html <- html_nodes(webpage, '.lister-item-header a')
title_data <- html_text(title_data_html)


# scrape the descriptions
description_data_html <- html_nodes(webpage, '.ratings-bar+ .text-muted')
description_data <- html_text(description_data_html)

	# descriptions are now in a vector of character strings
		# but there is a "\n" at the start of each string
		# so we need to clean it

description_data <- gsub("\n", "", description_data)


# now scrape runtime
runtime_data_html <- html_nodes(webpage, '.text-muted .runtime')
runtime_data <- html_text(runtime_data_html)

	# need to clean out the "XXX min" from each string

runtime_data <- as.numeric(
					gsub(" min", "", runtime_data))


# scrape genre
genre_data_html <- html_nodes(webpage, '.genre')
genre_data <- html_text(genre_data_html)

genre_data <- gsub("\n", "", genre_data)
genre_data <- gsub(" ", "", genre_data)
genre_data <- gsub(",.*", "", genre_data) # take only the first genre
genre_data <- as.factor(genre_data) # convert from character to factor



# scrape ratings
rating_data_html <- html_nodes(webpage, '.ratings-imdb-rating strong')
rating_data <- html_text(rating_data_html)

rating_data <- as.numeric(rating_data)


# scrape votes
votes_data_html <- html_nodes(webpage, '.sort-num_votes-visible span:nth-child(2)')
votes_data <- html_text(votes_data_html)

votes_data <- gsub(",", "", votes_data)
votes_data <- as.numeric(votes_data)


# scrape directors
director_data_html <- html_nodes(webpage, '.text-muted+ p a:nth-child(1)')
director_data <- html_text(director_data_html)

director_data <- as.factor(director_data)


# scrape actors and actresses
actor_data_html <- html_nodes(webpage, '.lister-item-content .ghost+ a')
actor_data <- html_text(actor_data_html)

actor_data <- as.factor(actor_data)



# scrape metascore
metascore_data_html <- html_nodes(webpage, '.metascore')
metascore_data <- html_text(metascore_data_html)

metascore_data <- gsub(" ", "", metascore_data)
metascore_data <- as.numeric(metascore_data)

	# there are a few missing metascores in the imdb page. 
		# you need to add NA's to respective row in the vector
		# THIS MAY CHANGE IF YOU RERUN THIS SCRIPT AT A LATTER DATE!
for (i in c(13, 23, 45)){
	a <- metascore_data[1:(i-1)]
	b <- metascore_data[i:length(metascore_data)]
	metascore_data <- append(a,list("NA"))
	metascore_data <- append(metascore_data, b)
}

metascore_data <- unlist(metascore_data)
metascore_data <- as.numeric(metascore_data)



# scrape film gross
gross_data_html <- html_nodes(webpage, '.ghost~ .text-muted+ span')
gross_data <- html_text(gross_data_html)

gross_data <- gsub("M","",gross_data)
gross_data <- substring(gross_data, 2, 6)

	# we've got a lot of missing values though
		# manually put in NAs
		# THIS MAY CHANGE IF YOU RERUN THIS SCRIPT AT A LATTER DATE
for (i in c(13,18,21,23,26,28,37,45,51,59,74,86,92,96,97)){
	a <- gross_data[1:(i-1)]
	b <- gross_data[i:length(gross_data)]
	gross_data <- append(a,list("NA"))
	gross_data <- append(gross_data,b)
}
gross_data <- unlist(gross_data)
gross_data <- as.numeric(gross_data)

summary(gross_data)




# Combine scraped vectors into a dataframe

movies_df <- data.frame(Rank = rank_data, Title = title_data, 
	Description = description_data, Runtime = runtime_data, Genre = genre_data,
	Rating = rating_data, Metascore = metascore_data, Votes = votes_data,
	Gross_Earning_in_Mil = gross_data, Director = director_data,
	Actor = actor_data)

str(movies_df)



# Analyzing scrapped data from the web
qplot(data = movies_df, Runtime,fill = Genre, bins = 30)

ggplot(movies_df, aes(x = Runtime, y = Rating)) + 
	geom_point(aes(size = Votes,col = Genre))


ggplot(movies_df, aes(x = Runtime, y = Gross_Earning_in_Mil)) + 
	geom_point(aes(size = Rating, col = Genre))
